"use client";

import { useState, useRef } from "react";
import { motion, AnimatePresence } from "framer-motion";
import { Share2, X, Download, Twitter, Copy, Check } from "lucide-react";
import { Button } from "@/components/ui/button";

interface Props {
  title: string;
  score: number;
  confidence: number;
  estimatedViews: string;
  channelName: string;
}

function SharePreviewCard({
  title, score, confidence, estimatedViews, channelName
}: Props) {
  return (
    <div
      id="share-card"
      className="w-full rounded-2xl overflow-hidden p-7"
      style={{
        background: "linear-gradient(135deg, #0B0F19 0%, #1a1040 50%, #0B0F19 100%)",
        border: "1px solid rgba(124,58,237,0.4)",
        boxShadow: "0 0 60px rgba(124,58,237,0.25)",
      }}
    >
      {/* Header */}
      <div className="flex items-center justify-between mb-5">
        <div className="flex items-center gap-2">
          <div className="w-7 h-7 rounded-lg bg-gradient-to-br from-violet-600 to-purple-700 flex items-center justify-center">
            <span className="text-white text-xs font-black">IQ</span>
          </div>
          <span className="text-sm font-bold text-white">UploadIQ</span>
        </div>
        <span className="text-xs text-violet-400 font-semibold">My Next Video Prediction</span>
      </div>

      {/* Title */}
      <h2 className="text-xl font-black text-white leading-tight mb-5 line-clamp-2">
        {title}
      </h2>

      {/* Metrics */}
      <div className="grid grid-cols-3 gap-3 mb-5">
        <div className="rounded-xl p-3 text-center" style={{ background: "rgba(34,197,94,0.1)", border: "1px solid rgba(34,197,94,0.2)" }}>
          <p className="text-2xl font-black text-green-400">{score}</p>
          <p className="text-[10px] text-green-300 mt-0.5 font-semibold uppercase tracking-wide">Opp. Score</p>
        </div>
        <div className="rounded-xl p-3 text-center" style={{ background: "rgba(34,197,94,0.1)", border: "1px solid rgba(34,197,94,0.2)" }}>
          <p className="text-2xl font-black text-white">{confidence}%</p>
          <p className="text-[10px] text-green-400 mt-0.5 font-semibold uppercase tracking-wide">Confidence</p>
        </div>
        <div className="rounded-xl p-3 text-center" style={{ background: "rgba(251,146,60,0.1)", border: "1px solid rgba(251,146,60,0.2)" }}>
          <p className="text-sm font-black text-white leading-tight">{estimatedViews}</p>
          <p className="text-[10px] text-orange-400 mt-0.5 font-semibold uppercase tracking-wide">Est. Views</p>
        </div>
      </div>

      {/* Footer */}
      <div className="flex items-center justify-between">
        <span className="text-xs text-muted-foreground">{channelName}</span>
        <span className="text-xs text-violet-400/70">uploadiq.com</span>
      </div>
    </div>
  );
}

export function ShareCard(props: Props) {
  const [open, setOpen] = useState(false);
  const [copied, setCopied] = useState(false);

  const shareText = `🎯 My next YouTube video prediction\n\n"${props.title}"\n\n📊 ${props.confidence}% confidence · Est. ${props.estimatedViews} views\n\nGenerated by @UploadIQ`;

  function handleCopy() {
    navigator.clipboard.writeText(shareText);
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
  }

  function handleTweet() {
    window.open(`https://twitter.com/intent/tweet?text=${encodeURIComponent(shareText)}`, "_blank");
  }

  function handlePrint() {
    const el = document.getElementById("share-card");
    if (!el) return;
    const w = window.open("", "_blank");
    if (!w) return;
    w.document.write(`<html><body style="background:#0B0F19;margin:0;padding:20px">${el.outerHTML}</body></html>`);
    w.document.close();
    w.print();
  }

  return (
    <>
      <Button
        variant="outline"
        size="sm"
        className="gap-2 h-9 text-xs border-white/[0.1] hover:border-accent/40 hover:text-accent"
        onClick={() => setOpen(true)}
      >
        <Share2 className="w-3.5 h-3.5" />
        Share
      </Button>

      <AnimatePresence>
        {open && (
          <motion.div
            initial={{ opacity: 0 }}
            animate={{ opacity: 1 }}
            exit={{ opacity: 0 }}
            className="fixed inset-0 bg-black/70 backdrop-blur-sm z-50 flex items-center justify-center p-4"
            onClick={() => setOpen(false)}
          >
            <motion.div
              initial={{ scale: 0.95, opacity: 0 }}
              animate={{ scale: 1, opacity: 1 }}
              exit={{ scale: 0.95, opacity: 0 }}
              transition={{ duration: 0.2 }}
              onClick={e => e.stopPropagation()}
              className="w-full max-w-md"
              style={{ background: "#111827", border: "1px solid rgba(255,255,255,0.08)", borderRadius: 16 }}
            >
              <div className="flex items-center justify-between px-5 py-4 border-b border-white/[0.06]">
                <p className="text-sm font-bold text-white">Share Your Prediction</p>
                <button onClick={() => setOpen(false)} className="text-muted-foreground hover:text-white">
                  <X className="w-4 h-4" />
                </button>
              </div>

              <div className="p-5">
                <SharePreviewCard {...props} />

                <div className="grid grid-cols-3 gap-2 mt-4">
                  <button
                    onClick={handleTweet}
                    className="flex flex-col items-center gap-2 p-3 rounded-xl border border-white/[0.07] hover:border-[#1DA1F2]/40 hover:bg-[#1DA1F2]/5 transition-all group"
                  >
                    <Twitter className="w-5 h-5 text-muted-foreground group-hover:text-[#1DA1F2]" />
                    <span className="text-xs text-muted-foreground group-hover:text-white">Share on X</span>
                  </button>
                  <button
                    onClick={handlePrint}
                    className="flex flex-col items-center gap-2 p-3 rounded-xl border border-white/[0.07] hover:border-accent/40 hover:bg-accent/5 transition-all group"
                  >
                    <Download className="w-5 h-5 text-muted-foreground group-hover:text-accent" />
                    <span className="text-xs text-muted-foreground group-hover:text-white">Download</span>
                  </button>
                  <button
                    onClick={handleCopy}
                    className="flex flex-col items-center gap-2 p-3 rounded-xl border border-white/[0.07] hover:border-green-400/40 hover:bg-green-400/5 transition-all group"
                  >
                    {copied
                      ? <Check className="w-5 h-5 text-green-400" />
                      : <Copy className="w-5 h-5 text-muted-foreground group-hover:text-green-400" />}
                    <span className="text-xs text-muted-foreground group-hover:text-white">{copied ? "Copied!" : "Copy Text"}</span>
                  </button>
                </div>
              </div>
            </motion.div>
          </motion.div>
        )}
      </AnimatePresence>
    </>
  );
}
